baseURL: https://pedroreys.com/
disablePathToLower: true
languageCode: en-us

title: Pedro Reys
theme: tale
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsOptions: "linenos=table,linenostart=1"
disqusShortname: pedroreys
googleAnalytics: UA-1861436-2

params:
    AuthorName: Pedro Reys
    GitHubUser: pedroreys
    css: ["css/dracula_highlight.css"]


